<Project Sdk="Cosmos.Sdk/3.0.89">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cosmos.Kernel" Version="3.0.89" />
    <PackageReference Include="Cosmos.Kernel.System" Version="3.0.89" />
  </ItemGroup>

</Project>